import re

text = '''
C:\code\Python\Python39\python.exe D:/code/1.py
 name="WHEAT" pricePerLiter="0.337"
 name="BARLEY" pricePerLiter="0.313"
 name="OAT" pricePerLiter="0.532"
 name="CANOLA" pricePerLiter="0.603"
 name="SUNFLOWER" pricePerLiter="0.673"
 name="SOYBEAN" pricePerLiter="0.778"
 name="MAIZE" pricePerLiter="0.380"
 name="POTATO" pricePerLiter="0.172"
 name="SUGARBEET" pricePerLiter="0.122"
 name="COTTON" pricePerLiter="1.252"
 name="SUGARCANE" pricePerLiter="0.119"
 name="SEEDS" pricePerLiter="0.9"
 name="EGG" pricePerLiter="1.5"
 name="WOOL" pricePerLiter="0.6"
 name="MILK" pricePerLiter="0.7"
 name="FUEL" pricePerLiter="1.1"
 name="WATER" pricePerLiter="0.1"
 name="FORAGE" pricePerLiter="0.042"
 name="FORAGE_MIXING" pricePerLiter="0.039"
 name="CHAFF" pricePerLiter="0.042"
 name="TREESAPLINGS" pricePerLiter="0.100"
 name="WOODCHIPS" pricePerLiter="0.08"
 name="SILAGE" pricePerLiter="0.171"
 name="OILSEEDRADISH" pricePerLiter="0.250"
 name="POPLAR" pricePerLiter="0.040"
 name="GRASS" pricePerLiter="0.045"
 name="GRASS_WINDROW" pricePerLiter="0.045"
 name="DRYGRASS" pricePerLiter="0.048"
 name="DRYGRASS_WINDROW" pricePerLiter="0.056"
 name="STRAW" pricePerLiter="0.041"
 name="DIESEL" pricePerLiter="1.25"
 name="DEF" pricePerLiter="1.25"
 name="AIR" pricePerLiter="0.0"
 name="ROUNDBALE" pricePerLiter="1.00"
 name="ROUNDBALE_GRASS" pricePerLiter="1.00"
 name="ROUNDBALE_DRYGRASS" pricePerLiter="1.00"
 name="ROUNDBALE_WHEAT" pricePerLiter="1.00"
 name="ROUNDBALE_BARLEY" pricePerLiter="1.00"
 name="SQUAREBALE" pricePerLiter="1.00"
 name="SQUAREBALE_WHEAT" pricePerLiter="1.00"
 name="SQUAREBALE_BARLEY" pricePerLiter="1.00"
 name="FERTILIZER" pricePerLiter="1.60"
 name="LIQUIDFERTILIZER" pricePerLiter="1.20"
 name="MANURE" pricePerLiter="0.033"
 name="LIQUIDMANURE" pricePerLiter="0.033"
 name="DIGESTATE" pricePerLiter="0.033"
 name="PIGFOOD" pricePerLiter="1.4"
 name="TARP" pricePerLiter="0"
 name="LIME" pricePerLiter="0.225"
 name="HERBICIDE" pricePerLiter="1.2"
 name="WEED" pricePerLiter="0"
 name="HORSE_TYPE_BEIGE" pricePerLiter="0"
 name="HORSE_TYPE_BLACK" pricePerLiter="0"
 name="HORSE_TYPE_BROWN" pricePerLiter="0"
 name="HORSE_TYPE_BROWN_WHITE" pricePerLiter="0"
 name="HORSE_TYPE_DARK_BROWN" pricePerLiter="0"
 name="HORSE_TYPE_GREY" pricePerLiter="0"
 name="HORSE_TYPE_LIGHT_BROWN" pricePerLiter="0"
 name="HORSE_TYPE_RED_BROWN" pricePerLiter="0"
 name="COW_TYPE_BROWN" pricePerLiter="5000"
 name="COW_TYPE_BROWN_WHITE" pricePerLiter="5000"
 name="COW_TYPE_BLACK" pricePerLiter="5000"
 name="COW_TYPE_BLACK_WHITE" pricePerLiter="5000"
 name="COW_TYPE_BRAHMAN_BROWN" pricePerLiter="5000"
 name="COW_TYPE_BRAHMAN_WHITE" pricePerLiter="5000"
 name="COW_TYPE_BRAHMAN_LIGHT_BROWN" pricePerLiter="5000"
 name="COW_TYPE_BRAHMAN_GREY" pricePerLiter="5000"
 name="SHEEP_TYPE_WHITE" pricePerLiter="4000"
 name="SHEEP_TYPE_BROWN" pricePerLiter="4000"
 name="SHEEP_TYPE_BLACK_WHITE" pricePerLiter="4000"
 name="SHEEP_TYPE_BLACK" pricePerLiter="4000"
 name="PIG_TYPE_RED" pricePerLiter="3000"
 name="PIG_TYPE_WHITE" pricePerLiter="3000"
 name="PIG_TYPE_BLACK_WHITE" pricePerLiter="3000"
 name="PIG_TYPE_BLACK" pricePerLiter="3000"
 name="CHICKEN_TYPE_BLACK" pricePerLiter="0"
 name="CHICKEN_TYPE_WHITE" pricePerLiter="0"
 name="CHICKEN_TYPE_BROWN" pricePerLiter="0"
 name="CHICKEN_TYPE_ROOSTER" pricePerLiter="0"

Process finished with exit code 0

'''

# q1 = re.findall(r'( name=\".+?\").+?(pricePerLiter=\".+?\")', text)
q1 = re.findall(r'name=\"(.+?)\" pricePerLiter="(.+?)\"', text)

for i in q1:
    print(i[0], i[1])
